apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jessesuen/kargo-advanced.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: guestbook-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-guestbook:*
    spec:
      destination:
        namespace: guestbook-{{path.basename}}
        # Replace name with the cluster name:
        name: demo
      project: guestbook
      source:
        path: app # default render path
        repoURL: https://github.com/jessesuen/kargo-advanced.git
        targetRevision: env/{{path.basename}}
